// API contract — single source of truth.
// Both mock/*.json (generated by scripts/gen_mocks.py) and the FastAPI
// responses (analytics_api/app/cache.py) conform to these shapes.

export type Station = "jemmal" | "monastir";
export type SeriesKey = Station | "total";

export interface OverviewStation {
  bookings_latest_day: number;
  revenue_passenger_paid_latest_day: number;
  revenue_station_fee_latest_day: number;
  real_bookings_latest_day: number;
  ghost_bookings_latest_day: number;
  active_vehicles: number | null;
  trips_latest_day: number | null;
}

export interface AnomalyFlag {
  date: string; // YYYY-MM-DD
  bookings: number;
  detectors: string[]; // subset of ["rolling_z","wow_z","iso"]
  zero_day: boolean;
}

export interface OverviewResponse {
  data_through: string; // latest full day in artifacts, YYYY-MM-DD
  totals: OverviewStation;
  stations: Record<Station, OverviewStation>;
  anomaly_today: Record<Station, AnomalyFlag | null>;
}

export interface FlowHourlyPoint {
  station: Station;
  hour: number;
  bookings: number;
  seats: number;
  revenue_station_fee: number;
}

export interface FlowHourlyResponse {
  data_through: string;
  series: FlowHourlyPoint[];
}

export interface FlowDailyPoint {
  station: Station;
  created_date: string;
  bookings: number;
  seats: number;
  revenue_passenger_paid: number;
  revenue_station_fee: number;
  real_bookings: number;
  ghost_bookings: number;
}

export interface FlowDailyResponse {
  data_through: string;
  series: FlowDailyPoint[];
}

export interface RevenueDailyPoint {
  created_date: string;
  passenger_paid: number;
  station_fee: number;
  real_passenger_paid: number;
}

export interface RealVsGhostPoint {
  date: string;
  real: number;
  ghost: number;
}

export interface RouteRevenuePoint {
  station: Station;
  destination_canonical: string;
  bookings: number;
  revenue_passenger_paid: number;
  revenue_station_fee: number;
  avg_ticket: number;
  ghost_rate: number;
}

export interface RevenueResponse {
  data_through: string;
  daily: RevenueDailyPoint[];
  real_vs_ghost: RealVsGhostPoint[];
  by_route: RouteRevenuePoint[];
}

export interface RoutesResponse {
  data_through: string;
  groups: string[];
  routes: RouteRevenuePoint[];
}

export interface FleetStationSummary {
  active_vehicles: number;
  trips_per_vehicle: number;
  avg_load_factor: number | null;
  capacity_coverage_pct: number | null;
}

export interface FleetDailyPoint {
  station: Station;
  date: string;
  trips: number;
  load_factor: number | null;
}

export interface FleetResponse {
  data_through: string;
  caveat: string;
  summary: Record<Station, FleetStationSummary>;
  daily: FleetDailyPoint[];
}

export interface ForecastPoint {
  date: string;
  yhat: number;
  lo: number;
  hi: number;
}

export interface ForecastSeries {
  station: SeriesKey;
  model: string;
  mape: number | null;
  mape_std: number | null;
  horizon_days: number;
  forecast: ForecastPoint[];
}

export interface PredVsActualPoint {
  station: SeriesKey;
  date: string;
  actual: number;
  predicted: number;
}

export interface ForecastResponse {
  data_through: string;
  disclaimer: string;
  forecasts: ForecastSeries[];
  pred_vs_actual: PredVsActualPoint[];
}

export interface AnomalyPoint {
  date: string;
  station: SeriesKey;
  bookings: number;
  detectors: string[];
  zero_day: boolean;
}

export interface AnomaliesResponse {
  data_through: string;
  anomalies: AnomalyPoint[];
}

export interface HealthResponse {
  status: "ok" | "degraded";
  cache_loaded_at: string | null;
  artifacts_path: string;
  tunnels: Record<Station, boolean>;
}

export interface LiveTick {
  type: "tick";
  at: string; // ISO timestamp
  live: boolean;
  last_seen: string | null;
  // A station entry is null when its tunnel query failed (degraded tick).
  stations: Record<
    Station,
    | {
        bookings_today: number;
        revenue_passenger_paid: number;
        real: number;
        ghost: number;
        anomaly_flag: boolean;
      }
    | null
  >;
}
